import assert from 'node:assert/strict';
import { boardPosts, createWallLink, newWallShareId, readWallShareId, safeWallUrl, safeWallImage, safeWallAttachment, sharedWallPost, exportWallCsv, orderWallPosts, reactionCount, validWallLocation, assertWallSize, youtubeEmbed, type WallCategory, type WallPost } from '../src/lib/learningWall.ts';

const board: WallCategory = { id: 'class-one', title: 'Lớp 8A', authorId: 'teacher-one' };
const categories: WallCategory[] = [board, { id: 'section-one', title: 'Nhóm 1', parentId: board.id, authorId: 'teacher-one' }, { id: 'foreign', title: 'Không được lấy', parentId: board.id, authorId: 'teacher-two' }];
const legacy: WallPost = { id: 'legacy', categoryId: 'section-one', studentName: 'Bình', authorId: 'teacher-one', teacherId: 'teacher-one', imageSrc: 'data:image/jpeg;base64,YQ==', createdAt: { seconds: 100 }, score: 0, comments: [{ id: 'c', text: 'Nhận xét riêng' }], likedBy: ['teacher-one'], likes: 2 };
const direct: WallPost = { id: 'root-post', categoryId: board.id, studentName: 'An', authorId: 'teacher-one', title: 'Tiêu đề', text: '=HYPERLINK("x")', createdAt: 200_000 };
const foreign: WallPost = { ...legacy, id: 'foreign-post', authorId: 'teacher-two', teacherId: 'teacher-two' };
assert.deepEqual(boardPosts(board, categories, [legacy, direct, foreign, { ...foreign, categoryId: 'foreign' }]).map(post => post.id), ['legacy', 'root-post'], 'Legacy category posts and new direct board posts survive; foreign owners stay excluded even for admin.');
assert.equal(reactionCount(legacy), 3);
assert.equal(reactionCount({ ...legacy, likedBy: ['x', 'x'] }), 3);
assert.deepEqual(orderWallPosts([legacy, direct], 'newest').map(post => post.id), ['root-post', 'legacy']);
assert.deepEqual(orderWallPosts([legacy, direct], 'oldest').map(post => post.id), ['legacy', 'root-post']);
assert.equal(orderWallPosts([legacy, direct], 'name', 'BÌNH')[0].id, 'legacy');
assert.equal(orderWallPosts([legacy, { ...direct, pinned: true }], 'oldest')[0].id, direct.id);
for (const url of ['javascript:alert(1)', 'data:text/html,a', 'file:///etc/passwd', 'https://user:pass@example.com', '//example.com']) assert.equal(safeWallUrl(url), '');
assert.equal(safeWallUrl('https://example.com/path'), 'https://example.com/path');
assert.equal(safeWallImage('data:image/svg+xml;base64,YQ=='), '');
assert.equal(safeWallAttachment({ id: 'x', name: 'attack', kind: 'file', url: 'data:text/html;base64,YQ==' }), '');
assert.equal(youtubeEmbed('https://youtube.com.evil.test/watch?v=abcdefghijk'), '');
assert.equal(youtubeEmbed('https://youtu.be/abcdefghijk'), 'https://www.youtube-nocookie.com/embed/abcdefghijk');
const publicPost = sharedWallPost({ ...legacy, attachments: [{ id: 'f', kind: 'link', name: 'Tài liệu', url: 'https://example.com', privateNote: 'secret' } as any] });
for (const key of ['authorId', 'teacherId', 'ownerUid', 'score', 'comments', 'likedBy']) assert.equal(key in publicPost, false, `${key} must never be published`);
assert.equal(JSON.stringify(publicPost).includes('secret'), false);
const csv = exportWallCsv([legacy, direct]); assert.ok(csv.startsWith('\uFEFF')); assert.ok(csv.includes('"0"')); assert.ok(csv.includes("'=HYPERLINK"));
assert.throws(() => assertWallSize({ text: 'a'.repeat(800_000) }));
assert.equal(validWallLocation(21.5, 105.7), true); assert.equal(validWallLocation(NaN, 105), false); assert.equal(validWallLocation(91, 0), false);
const token = newWallShareId(); assert.match(token, /^[a-f0-9]{48}$/); assert.equal(readWallShareId(`#wall=${token}`), token); assert.equal(readWallShareId('#wall=guess'), '');
const url = new URL(createWallLink('/4.0/', 'https://school.test', token)); assert.equal(url.searchParams.get('app'), 'learning-wall'); assert.equal(url.hash, `#wall=${token}`); assert.ok(!url.search.includes(token));
console.info('Learning Wall: legacy compatibility, owner isolation, redaction, media safety, CSV, layouts and sharing tests passed.');
